/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2_p1;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author btlbi
 */
public class ISTANBUL_services extends javax.swing.JFrame {

    /**
     * Creates new form ISTANBUL_services
     */
    public ISTANBUL_services() {
        initComponents();
        panel_pink.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        panel_pinkd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        pnl_top = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel_pink = new javax.swing.JPanel();
        lbl_three = new javax.swing.JLabel();
        lbl_two = new javax.swing.JLabel();
        lbl_one = new javax.swing.JLabel();
        lbl_THREE = new javax.swing.JLabel();
        lbl_ONE = new javax.swing.JLabel();
        lbl_THREE1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        item_exit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        item_read = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_pinkd.setBackground(new java.awt.Color(255, 153, 153));
        panel_pinkd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e66fbe79ce5ed5427f775fdf944d3c17 (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        panel_pinkd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 80, 170, 140));

        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_back.setText("Back to main menu");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_pinkd.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 160, 40));

        pnl_top.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INSTITUTIONAL SERVICES OF ISTANBUL");

        javax.swing.GroupLayout pnl_topLayout = new javax.swing.GroupLayout(pnl_top);
        pnl_top.setLayout(pnl_topLayout);
        pnl_topLayout.setHorizontalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_topLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel7)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        pnl_topLayout.setVerticalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_topLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panel_pinkd.add(pnl_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        jButton1.setText("SEE THE PLACES TO VISIT IN ISTANBUL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_pinkd.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 270, 50));

        panel_pink.setBackground(new java.awt.Color(255, 204, 204));

        lbl_three.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1 (1).jpg"))); // NOI18N
        lbl_three.setText("jLabel1");

        lbl_two.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/istanbul-tarihi-yerler-galata-ku.jpg"))); // NOI18N
        lbl_two.setText("jLabel1");

        lbl_one.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutterstock_158441717 (1).jpg"))); // NOI18N
        lbl_one.setText("jLabel1");

        lbl_THREE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_THREE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_THREE.setText("AYASOFYA");

        lbl_ONE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ONE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ONE.setText("DOLMABAHÇE");

        lbl_THREE1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_THREE1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_THREE1.setText("GALATA");

        javax.swing.GroupLayout panel_pinkLayout = new javax.swing.GroupLayout(panel_pink);
        panel_pink.setLayout(panel_pinkLayout);
        panel_pinkLayout.setHorizontalGroup(
            panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pinkLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_one, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_two, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_three, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pinkLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lbl_ONE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(lbl_THREE1)
                .addGap(206, 206, 206)
                .addComponent(lbl_THREE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_pinkLayout.setVerticalGroup(
            panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pinkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_three, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_two, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_one, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ONE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_THREE1)
                    .addComponent(lbl_THREE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panel_pinkd.add(panel_pink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 770, 160));

        jMenu2.setText("SERVICES IN ISTANBUL");

        jMenuItem1.setText("HEALTH");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("CIMER");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);
        jMenu2.add(jSeparator2);

        jMenuItem3.setText("SPORTS");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");

        jCheckBoxMenuItem1.setText("DARK MODE");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem1);

        item_exit.setText("EXIT");
        item_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_exitActionPerformed(evt);
            }
        });
        jMenu3.add(item_exit);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("History");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        item_read.setText("Read");
        item_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_readActionPerformed(evt);
            }
        });
        jMenu4.add(item_read);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pinkd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pinkd, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Health_MAKE().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CIMER_apply().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
//gives info. about the cities history
    private void item_readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_readActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Istanbul, a crucial city in Turkish history,"
                + " was conquered by the Ottomans in 1453, marking the end of the Byzantine Empire. "
                );
    }//GEN-LAST:event_item_readActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void item_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_exitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Main_Menu().setVisible(true);
    }//GEN-LAST:event_item_exitActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Main_Menu().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panel_pink.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
//changes the background when user clicked the check box menu item
    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxMenuItem1.isSelected()){
            pnl_top.setBackground(Color.BLACK);
            panel_pink.setBackground(Color.BLACK);
            panel_pinkd.setBackground(Color.BLACK);
        }
        else{
            pnl_top.setBackground(Color.PINK);
            panel_pink.setBackground(Color.PINK);
            panel_pinkd.setBackground(Color.PINK);
        }
        
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Sport_ISTANBUL().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ISTANBUL_services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ISTANBUL_services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ISTANBUL_services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ISTANBUL_services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISTANBUL_services().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JMenuItem item_exit;
    private javax.swing.JMenuItem item_read;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lbl_ONE;
    private javax.swing.JLabel lbl_THREE;
    private javax.swing.JLabel lbl_THREE1;
    private javax.swing.JLabel lbl_one;
    private javax.swing.JLabel lbl_three;
    private javax.swing.JLabel lbl_two;
    private javax.swing.JPanel panel_pink;
    private javax.swing.JPanel panel_pinkd;
    private javax.swing.JPanel pnl_top;
    // End of variables declaration//GEN-END:variables
}
