/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2_p1;

import java.awt.Color;

/**
 *
 * @author btlbi
 */
public class SAMSUN_services extends javax.swing.JFrame {

    /**
     * Creates new form SAMSUN_services
     */
    public SAMSUN_services() {
        initComponents();
        panel_pink.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        pnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panel_pink = new javax.swing.JPanel();
        lbl_three = new javax.swing.JLabel();
        lbl_two = new javax.swing.JLabel();
        lbl_one = new javax.swing.JLabel();
        lbl_THREE = new javax.swing.JLabel();
        lbl_TWO = new javax.swing.JLabel();
        lbl_ONE = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        health = new javax.swing.JMenuItem();
        cimer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/20210830185858!Samsun_Büyükşehir (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 140));

        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_back.setText("Back to main menu");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 150, 50));

        pnl.setBackground(new java.awt.Color(255, 204, 204));
        pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INSTITUTIONAL SERVICES OF SAMSUN");
        pnl.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 32));

        jPanel1.add(pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 70));

        panel_pink.setBackground(new java.awt.Color(255, 204, 204));

        lbl_three.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kizilirmak-samsun-gezilecek-yerl.jpg"))); // NOI18N
        lbl_three.setText("jLabel1");

        lbl_two.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/amisos-tepesi-samsun-gezilecek-y.jpg"))); // NOI18N
        lbl_two.setText("jLabel1");

        lbl_one.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lets-go-karadeniz-08-825x6001 (1).jpg"))); // NOI18N
        lbl_one.setText("jLabel1");

        lbl_THREE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_THREE.setText("LOVE LAKE");

        lbl_TWO.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TWO.setText("AMISOS HILL");

        lbl_ONE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ONE.setText("NATIONAL LIBERATION MONUMENT");

        javax.swing.GroupLayout panel_pinkLayout = new javax.swing.GroupLayout(panel_pink);
        panel_pink.setLayout(panel_pinkLayout);
        panel_pinkLayout.setHorizontalGroup(
            panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pinkLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pinkLayout.createSequentialGroup()
                        .addComponent(lbl_ONE)
                        .addGap(114, 114, 114)
                        .addComponent(lbl_TWO, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_THREE)
                        .addGap(118, 118, 118))
                    .addGroup(panel_pinkLayout.createSequentialGroup()
                        .addComponent(lbl_one, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lbl_two, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lbl_three, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        panel_pinkLayout.setVerticalGroup(
            panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pinkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_three, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_two, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_one, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_pinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ONE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TWO, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_THREE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(panel_pink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 780, 170));

        jButton1.setText("SEE THE PLACES TO VISIT IN SAMSUN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 270, 50));

        jMenu1.setText("SERVICES IN SAMSUN");

        health.setText("HEALTH");
        health.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthActionPerformed(evt);
            }
        });
        jMenu1.add(health);

        cimer.setText("CIMER");
        cimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cimerActionPerformed(evt);
            }
        });
        jMenu1.add(cimer);
        jMenu1.add(jSeparator1);

        jMenuItem1.setText("SPORT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("EDIT");

        jCheckBoxMenuItem1.setText("DARK MODE");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Main_Menu().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panel_pink.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
//changes the background when user clicked the check box menu item
    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxMenuItem1.isSelected()){
            pnl.setBackground(Color.BLACK);
            jPanel1.setBackground(Color.BLACK);
            panel_pink.setBackground(Color.BLACK);
        }
        else{
            pnl.setBackground(Color.PINK);
            jPanel1.setBackground(Color.PINK);
            panel_pink.setBackground(Color.PINK);
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void healthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Health_MAKE().setVisible(true);
    }//GEN-LAST:event_healthActionPerformed

    private void cimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cimerActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new CIMER_apply().setVisible(true);
    }//GEN-LAST:event_cimerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new Sport_SAMSUN().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAMSUN_services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAMSUN_services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAMSUN_services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAMSUN_services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAMSUN_services().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JMenuItem cimer;
    private javax.swing.JMenuItem health;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbl_ONE;
    private javax.swing.JLabel lbl_THREE;
    private javax.swing.JLabel lbl_TWO;
    private javax.swing.JLabel lbl_one;
    private javax.swing.JLabel lbl_three;
    private javax.swing.JLabel lbl_two;
    private javax.swing.JPanel panel_pink;
    private javax.swing.JPanel pnl;
    // End of variables declaration//GEN-END:variables
}
