/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2_p1;

import javax.swing.JOptionPane;

/**
 *
 * @author btlbi
 */
public class Sport_ISTANBUL extends javax.swing.JFrame {

    /**
     * Creates new form Sport_ISTANBUL
     */
    public Sport_ISTANBUL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_pinkd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_reg = new javax.swing.JButton();
        pnl_top = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_ONE = new javax.swing.JLabel();
        lbl_ONE1 = new javax.swing.JLabel();
        lbl_ONE2 = new javax.swing.JLabel();
        lbl_ONE3 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        txt_name2 = new javax.swing.JTextField();
        spinner = new javax.swing.JSpinner();
        cbox = new javax.swing.JComboBox<>();
        btn_back1 = new javax.swing.JButton();
        chck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_pinkd.setBackground(new java.awt.Color(255, 153, 153));
        panel_pinkd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e66fbe79ce5ed5427f775fdf944d3c17 (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        panel_pinkd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 80, 170, 140));

        btn_reg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reg.setText("REGISTER");
        btn_reg.setEnabled(false);
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });
        panel_pinkd.add(btn_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 160, 40));

        pnl_top.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SPORT SERVICES OF ISTANBUL");

        javax.swing.GroupLayout pnl_topLayout = new javax.swing.GroupLayout(pnl_top);
        pnl_top.setLayout(pnl_topLayout);
        pnl_topLayout.setHorizontalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_topLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel7)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        pnl_topLayout.setVerticalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_topLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panel_pinkd.add(pnl_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        lbl_ONE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ONE.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ONE.setText("CHOOSE A SPORT COURSE:");
        panel_pinkd.add(lbl_ONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        lbl_ONE1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ONE1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ONE1.setText("AGE:");
        panel_pinkd.add(lbl_ONE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        lbl_ONE2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ONE2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ONE2.setText("NAME:");
        panel_pinkd.add(lbl_ONE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        lbl_ONE3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ONE3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ONE3.setText("SURNAME");
        panel_pinkd.add(lbl_ONE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));
        panel_pinkd.add(txt_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 100, -1));
        panel_pinkd.add(txt_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, -1));

        spinner.setModel(new javax.swing.SpinnerNumberModel(18, 18, null, 1));
        panel_pinkd.add(spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming course", "Tennis course", "Football course" }));
        panel_pinkd.add(cbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        btn_back1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_back1.setText("Back to Istanbul services");
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });
        panel_pinkd.add(btn_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 180, 40));

        chck.setText("I confirm the accuracy of my information");
        chck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckActionPerformed(evt);
            }
        });
        panel_pinkd.add(chck, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pinkd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pinkd, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//the sport and the persons info save in the sport_table with the id which increase one by one.

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        // TODO add your handling code here:
        String s=spinner.getValue()+"";
        String n=txt_name2.getText();
        String sn=txt_surname.getText();
        String sport=cbox.getSelectedItem().toString();
        if(n!=null&&sn!=null){
            DB_Manager.AddSport(n, sn, s, sport);
            JOptionPane.showMessageDialog(rootPane, " Your registration has been created successfully");
        }
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ISTANBUL_services().setVisible(true);
    }//GEN-LAST:event_btn_back1ActionPerformed

    private void chckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckActionPerformed
        // TODO add your handling code here:
        if(chck.isSelected()){
            btn_reg.setEnabled(true);
        }
    }//GEN-LAST:event_chckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sport_ISTANBUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sport_ISTANBUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sport_ISTANBUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sport_ISTANBUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sport_ISTANBUL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_reg;
    private javax.swing.JComboBox<String> cbox;
    private javax.swing.JCheckBox chck;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_ONE;
    private javax.swing.JLabel lbl_ONE1;
    private javax.swing.JLabel lbl_ONE2;
    private javax.swing.JLabel lbl_ONE3;
    private javax.swing.JPanel panel_pinkd;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JSpinner spinner;
    private javax.swing.JTextField txt_name2;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
}
