/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bp2_p1;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author btlbi
 */
public class sport_INQ extends javax.swing.JFrame {
    DefaultListModel dl;
    String id=DB_Manager.id+"";
    /**
     * Creates new form sport_INQ
     */
    public sport_INQ() {
        initComponents();
        dl=new DefaultListModel();
        jList1.setModel(dl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Green = new javax.swing.JMenuItem();
        Red = new javax.swing.JMenuItem();
        Purple = new javax.swing.JMenuItem();
        panel_pinkd = new javax.swing.JPanel();
        pnl_top = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_back1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btn_show = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        Green.setText("Green");
        Green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Green);

        Red.setText("Red");
        Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Red);

        Purple.setText("Purple");
        Purple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurpleActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Purple);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_pinkd.setBackground(new java.awt.Color(255, 153, 153));
        panel_pinkd.setComponentPopupMenu(jPopupMenu1);
        panel_pinkd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_top.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SPORT INQUIRY SYSTEM ");

        javax.swing.GroupLayout pnl_topLayout = new javax.swing.GroupLayout(pnl_top);
        pnl_top.setLayout(pnl_topLayout);
        pnl_topLayout.setHorizontalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_topLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel7)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        pnl_topLayout.setVerticalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_topLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panel_pinkd.add(pnl_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        btn_back1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_back1.setText("Back to Main Menu");
        btn_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back1ActionPerformed(evt);
            }
        });
        panel_pinkd.add(btn_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 180, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/genclik-ve-spor-bakanligi-1325 (1).jpg"))); // NOI18N
        panel_pinkd.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        btn_show.setText("SHOW");
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });
        panel_pinkd.add(btn_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jList1.setToolTipText("");
        jScrollPane1.setViewportView(jList1);

        panel_pinkd.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("TAX INFORMATION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_pinkd.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pinkd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pinkd, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(jPopupMenu1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Main_Menu().setVisible(true);
    }//GEN-LAST:event_btn_back1ActionPerformed
//Informations of user can take from sport_table thanks to DB_Manager.SearchByID method
    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
        // TODO add your handling code here:
        DB_Manager.SearchByID(id);
        dl.add(0, "NAME: "+DB_Manager.s_n);
        dl.add(1, "SURNAME: "+DB_Manager.s_sn);
        dl.add(2, "AGE: "+DB_Manager.s_age);
        dl.add(3, "SPORT: "+DB_Manager.s_sport);
    }//GEN-LAST:event_btn_showActionPerformed
//Overload_taxMethod is using to get the tax info related to users age which is taken from the database with the help of DB_Manager.SearchByID method
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, Overload_taxMethod.s(DB_Manager.s_age,DB_Manager.s_n));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenActionPerformed
        panel_pinkd.setBackground(Color.green);
    }//GEN-LAST:event_GreenActionPerformed

    private void RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedActionPerformed
        panel_pinkd.setBackground(Color.red);
    }//GEN-LAST:event_RedActionPerformed

    private void PurpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurpleActionPerformed
        panel_pinkd.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_PurpleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sport_INQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sport_INQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sport_INQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sport_INQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sport_INQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Green;
    private javax.swing.JMenuItem Purple;
    private javax.swing.JMenuItem Red;
    private javax.swing.JButton btn_back1;
    private javax.swing.JButton btn_show;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_pinkd;
    private javax.swing.JPanel pnl_top;
    // End of variables declaration//GEN-END:variables
}
